//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CagriMerkeziV._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorev
    {
        public int ID { get; set; }
        public string GorevAdi { get; set; }
        public string GorevDetay { get; set; }
        public Nullable<int> GorevSahibiID { get; set; }
        public Nullable<System.DateTime> YapilacakSTarih { get; set; }
    
        public virtual Calisan Calisan { get; set; }
    }
}
