//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CagriMerkeziV._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorumsmeKaydi
    {
        public int ID { get; set; }
        public string ArananKisi { get; set; }
        public string ArananNo { get; set; }
        public string GorusmeNotu { get; set; }
        public Nullable<System.DateTime> GorusmeTar { get; set; }
        public Nullable<System.DateTime> ErtelemeTar { get; set; }
        public string GorusmeDurumu { get; set; }
    }
}
